name: Release

on:
  push:
    paths:
      - 'ilist.txt'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  make-custom:
    runs-on: ubuntu-latest
    name: Make custom for ${{ matrix.platform }}

    strategy:
      matrix:
        platform: [ ios, android ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python make_custom.py ${{ matrix.platform }}

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: custom
          path: custom-*.zip

  release:
    name: Release
    needs: make-custom
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Get current date
        id: date
        run: |
          echo "DATE=$(python -c 'from datetime import date; print(date.today().isoformat())')" >> $GITHUB_ENV

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: custom
          path: .

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.DATE }}
          tag_name: ${{ env.DATE }}
          files: custom-*.zip