name: Update ilist.txt

on:
  schedule:
    # Runs at the start of every hour
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}

      - name: Download ilist.txt
        run: |
          curl -o ilist.txt https://cdn.megagamelog.com/cross/release/ilist.txt

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update ilist.txt
